# docker-compose.yml
# La ligne 'version' est retirée pour éviter l'avertissement

services:
  # --- Service pour le serveur NATS avec JetStream ---
  nats_hub:
    image: nats:latest
    container_name: nats_hub
    ports:
      - "${NATS_CLIENT_PORT}:4222"
      - "${NATS_MONITORING_PORT}:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - jetstream-data:/data
    env_file:
      - .env
    command: "-c /etc/nats/nats.conf"
    restart: unless-stopped
    networks:
      nats-network:
        aliases:
          - nats_hub
      monitoring_net:
        # join shared monitoring network
        # no alias needed here


  # --- Service pour l'interface web NATS Surveyor ---
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest # 👈 This is the corrected line
    container_name: nats_exporter
    command: "-connz -routez -subz -varz http://nats_hub:8222"
    depends_on:
      - nats_hub
    restart: unless-stopped
    networks:
      - monitoring_net # 👈 Join the shared network
      - nats-network 

volumes:
  jetstream-data:
    name: ${COMPOSE_PROJECT_NAME}_jetstream_data

networks:
  monitoring_net:
    external: true
  nats-network:
    name: nats-network