# docker-compose.yml
# La ligne 'version' est retirée pour éviter l'avertissement

services:
  # --- Service pour le serveur NATS avec JetStream ---
  nats:
    image: nats:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nats
    ports:
      - "${NATS_CLIENT_PORT}:4222"
      - "${NATS_MONITORING_PORT}:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - jetstream-data:/data
    env_file:
      - .env
    command: "-js -m 8222" # -js enables JetStream, -m 8222 enables monitoring
    restart: unless-stopped
    networks:
      - nats-network
      - monitoring_net # 👈 Join the shared network


  # --- Service pour l'interface web NATS Surveyor ---
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest # 👈 This is the corrected line
    container_name: nats_exporter
    command: "-connz -routez -subz -varz http://nats:8222"
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - monitoring_net # 👈 Join the shared network
      - nats-network 

volumes:
  jetstream-data:
    name: ${COMPOSE_PROJECT_NAME}_jetstream_data

networks:
  nats-network:
    name: nats-network
  monitoring_net:
    external: true