# docker-compose.yml
# La ligne 'version' est retirée pour éviter l'avertissement

services:
  # --- Service pour le serveur NATS avec JetStream ---
  nats:
    image: nats:latest
    container_name: ${COMPOSE_PROJECT_NAME}_nats
    ports:
      - "${NATS_CLIENT_PORT}:4222"
      - "${NATS_MONITORING_PORT}:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - jetstream-data:/data
    env_file:
      - .env
    command: "--config /etc/nats/nats.conf"
    restart: unless-stopped


  # --- Service pour l'interface web NATS Surveyor ---
  webui:
    image: sphqxe/nats-webui:latest
    container_name: ${COMPOSE_PROJECT_NAME}_webui
    ports:
      - "${SURVEYOR_PORT}:80"
    depends_on:
      nats:
        condition: service_started
    restart: unless-stopped

volumes:
  jetstream-data:
    name: ${COMPOSE_PROJECT_NAME}_jetstream_data