version: "3"

services:
  sonarqube:
    image: sonarqube:9.9.2-community # Pinned version for stability
    container_name: sonarqube
    ports:
      - "${SONARQUBE_PORT:-9999}:9000" # Le port par défaut de SonarQube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar # URL de connexion à la DB
      - SONARQUBE_JDBC_USERNAME=sonar # Nom d'utilisateur de la DB
      - SONARQUBE_JDBC_PASSWORD=sonar # Use environment variable with default
      - SONAR_WEB_JAVAOPTS=-Xmx1g -Xms512m -XX:+HeapDumpOnOutOfMemoryError # Increased memory allocation
      - SONAR_CE_JAVAOPTS=-Xmx512m -Xms256m -XX:+HeapDumpOnOutOfMemoryError
      - SONAR_SEARCH_JAVAOPTS=-Xmx512m -Xms256m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError
    volumes:
      - sonarqube_data:/opt/sonarqube/data # Persistance des données de SonarQube
      - sonarqube_extensions:/opt/sonarqube/extensions # Persistance des plugins
      - sonarqube_logs:/opt/sonarqube/logs # Persistance des logs
    depends_on:
      - sonarqube_db # S'assure que la DB démarre avant SonarQube

  sonarqube_db:
    image: postgres:15.4-alpine # Pinned version with smaller alpine base image
    container_name: sonarqube_db
    ports:
      - "${POSTGRES_PORT:-9998}:5432"
    environment:
      - POSTGRES_USER=sonar # Nom d'utilisateur de la DB (doit correspondre à SonarQube)
      - POSTGRES_PASSWORD=sonar # Mot de passe de la DB (doit correspondre à SonarQube)
      - POSTGRES_DB=sonar # Nom de la base de données (doit correspondre à SonarQube)
    volumes:
      - ./${POSTGRES_VOLUME_FOLDER:-sonar-postgresql-data}/:/var/lib/postgresql/data/ # Persistance des données de la DB

  pgadmin:
    container_name: sonar_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-securepassword123}
    ports:
      - "${PGADMIN_PORT:-9997}:80"
    volumes:
      - ./${PGADMIN_VOLUME_FOLDER:-sonar-pgadmin-data}/:/var/lib/pgadmin

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: