global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nats'
    scrape_interval: 15s
    static_configs:
      - targets: ['nats-exporter:7777'] # This will now work across projects
